"""Integrações = permissões de fontes externas da ARKHER.

Não são provedores de IA. Cada cartão autoriza a ARKHER a usar *aquela*
fonte/ferramenta com o consentimento do usuário. O chat continua sendo a
super-IA; daqui saem só pontes e credenciais.
"""
from __future__ import annotations

CATALOGO: list[dict] = [
    {
        "id": "github",
        "nome": "GitHub",
        "categoria": "código",
        "descricao": "Repos seus: puxar/push de places, scripts e o PC virtual. Cole um PAT com repo se quiser sync.",
        "precisa_token": True,
        "token_hint": "ghp_… (escopo repo)",
    },
    {
        "id": "blender",
        "nome": "Blender",
        "categoria": "3D",
        "descricao": "Addon-ponte e execução de scripts .py gerados no chat, no Blender aberto (local ou Workspace).",
        "precisa_token": False,
        "arquivo": "arkher_ponte_blender.py",
        "rota": "/api/build/plugin-blender",
    },
    {
        "id": "roblox",
        "nome": "Roblox Studio",
        "categoria": "3D",
        "descricao": "Plugin-ponte e importação de .rbxlx/.rbxmx no Studio aberto, sempre com a sua permissão.",
        "precisa_token": False,
        "arquivo": "arkher_ponte_roblox.lua",
        "rota": "/api/build/plugin",
    },
    {
        "id": "youtube",
        "nome": "YouTube",
        "categoria": "referência",
        "descricao": "Pesquisa licenciada de referências (sua chave Data API). Sem chave, a ARKHER não inventa que assistiu o vídeo.",
        "precisa_token": True,
        "token_hint": "chave da YouTube Data API v3",
    },
    {
        "id": "google",
        "nome": "Google (Drive/Docs)",
        "categoria": "arquivos",
        "descricao": "Ler briefs e refs nos *seus* Docs/Drive. Só com OAuth/token seu; nada de conta da ARKHER.",
        "precisa_token": True,
        "token_hint": "token OAuth de aplicativo seu",
    },
    {
        "id": "figma",
        "nome": "Figma",
        "categoria": "design",
        "descricao": "Ler frames e tokens de UI do seu arquivo Figma (token pessoal) para HUD/menus no jogo.",
        "precisa_token": True,
        "token_hint": "figd_…",
    },
    {
        "id": "huggingface",
        "nome": "Hugging Face (operários)",
        "categoria": "treino",
        "descricao": "Operários no *seu* hardware geram/filtram dados licenciados para treinar a ARKHER. Não usa modelo HF no chat.",
        "precisa_token": True,
        "token_hint": "hf_… (write no seu repo privado)",
    },
    {
        "id": "kaggle",
        "nome": "Kaggle",
        "categoria": "treino",
        "descricao": "Nó de GPU gratuito (~30 h/semana) para treinar o próximo checkpoint ARKHER, a partir do anterior.",
        "precisa_token": False,
    },
    {
        "id": "colab",
        "nome": "Google Colab",
        "categoria": "treino",
        "descricao": "Notebook de treino/render na sua conta Colab. Mesma regra: pesos ARKHER, sem modelo de terceiro no runtime.",
        "precisa_token": False,
    },
    {
        "id": "discord",
        "nome": "Discord",
        "categoria": "comunidade",
        "descricao": "Webhook seu para avisar fim de build/treino. A ARKHER não lê o servidor inteiro.",
        "precisa_token": True,
        "token_hint": "URL do webhook",
    },
    {
        "id": "unity",
        "nome": "Unity",
        "categoria": "engine",
        "descricao": "Export glTF/FBX e scripts C# gerados no chat para o seu projeto Unity.",
        "precisa_token": False,
    },
    {
        "id": "unreal",
        "nome": "Unreal Engine",
        "categoria": "engine",
        "descricao": "Receitas de Blueprint/Datasmith e meshes glTF para o seu projeto Unreal.",
        "precisa_token": False,
    },
    {
        "id": "godot",
        "nome": "Godot",
        "categoria": "engine",
        "descricao": "Scenes .tscn e GDScript gerados no chat, importáveis no Godot 4.",
        "precisa_token": False,
    },
    {
        "id": "itch",
        "nome": "itch.io",
        "categoria": "publicação",
        "descricao": "Butler/API da *sua* conta para publicar builds. Nunca publica sem confirmação.",
        "precisa_token": True,
        "token_hint": "chave butler/API",
    },
    {
        "id": "sketchfab",
        "nome": "Sketchfab",
        "categoria": "referência",
        "descricao": "Busca de referências CC-licenciadas. Download só com licença explícita.",
        "precisa_token": True,
        "token_hint": "token Sketchfab",
    },
    {
        "id": "wikipedia",
        "nome": "Wikipedia",
        "categoria": "conhecimento",
        "descricao": "Fonte aberta CC BY-SA já usada no pipeline de treino e na pesquisa licenciada.",
        "precisa_token": False,
    },
    {
        "id": "archive",
        "nome": "Internet Archive",
        "categoria": "conhecimento",
        "descricao": "Itens com licença declarada para o corpus. Sem licença, não entra.",
        "precisa_token": False,
    },
    {
        "id": "tailscale",
        "nome": "Tailscale",
        "categoria": "rede",
        "descricao": "Rede da sua malha: o Workspace usa o IP 100.x para falar com o agente no PC virtual.",
        "precisa_token": True,
        "token_hint": "auth key reutilizável (opcional)",
    },
    {
        "id": "termux",
        "nome": "Termux / Android",
        "categoria": "acervo",
        "descricao": "Acervo em /storage/emulated/0/ArkherAITraining — converte rbxl/rbxm → rbxlx/rbxmx e organiza XML.",
        "precisa_token": False,
    },
    {
        "id": "vscode",
        "nome": "VS Code",
        "categoria": "código",
        "descricao": "Abrir os scripts/places gerados no editor do Workspace ou local.",
        "precisa_token": False,
    },
    {
        "id": "aseprite",
        "nome": "Aseprite",
        "categoria": "2D",
        "descricao": "Sprites e tiles gerados no chat exportados para o seu Aseprite (JSON + PNG).",
        "precisa_token": False,
    },
    {
        "id": "gimp",
        "nome": "GIMP",
        "categoria": "2D",
        "descricao": "Texturas PNG/XCF geradas no chat para pintura e baking no GIMP.",
        "precisa_token": False,
    },
]
