// Integrações: conectores legítimos com ferramentas abertas (Blender, Roblox, render nodes).

import { el, toast } from "../components/ui";
import { icon } from "../components/icons";
import { t } from "../services/i18n";
import type { Ctx } from "../app/app";

type Lang = "pt" | "en";

const CONECTORES: {
  id: string;
  nome: Record<Lang, string>;
  desc: Record<Lang, string>;
  arquivo: string;
  rota: string;
}[] = [
  {
    id: "blender",
    nome: { pt: "Blender — addon/ponte", en: "Blender — addon/bridge" },
    desc: {
      pt: "Instale o addon no Blender (Edit → Preferences → Add-ons → Install). Ele lê o script .py gerado pela ARKHER e cria a cena, personagem, terreno ou animação no seu arquivo aberto.",
      en: "Install the addon in Blender (Edit → Preferences → Add-ons → Install). It reads the .py script generated by ARKHER and builds the scene in your open file.",
    },
    arquivo: "arkher_ponte_blender.py",
    rota: "/api/build/plugin-blender",
  },
  {
    id: "roblox",
    nome: { pt: "Roblox Studio — plugin/ponte", en: "Roblox Studio — plugin/bridge" },
    desc: {
      pt: "Salve como plugin no Roblox Studio (Plugins → salvar .lua na pasta de plugins). A ponte abre o lugar .rbxlx gerado pela ARKHER dentro do seu place atual, peça por peça, com sua permissão.",
      en: "Save as a plugin in Roblox Studio (Plugins → save .lua in the plugins folder). The bridge opens the .rbxlx generated by ARKHER inside your current place, piece by piece, with your permission.",
    },
    arquivo: "arkher_ponte_roblox.lua",
    rota: "/api/build/plugin",
  },
];

export function renderIntegrations(ctx: Ctx): HTMLElement {
  const lang = ctx.store.state.settings.lang;
  const L: Lang = lang === "en" ? "en" : "pt";
  const root = el("div", { class: "panel" });
  root.append(el("h1", {}, t("integrations_title", lang)));
  root.append(el("p", { class: "dim" }, t("integrations_hint", lang)));

  const grid = el("div", { class: "tools-grid" });
  root.append(grid);

  for (const c of CONECTORES) {
    const card = el("div", { class: "tool-card" });
    card.append(el("h3", {}, c.nome[L]), el("p", {}, c.desc[L]));
    const btn = el("button", { class: "pri" });
    btn.append(icon("download", 14), " " + c.arquivo);
    btn.onclick = async () => {
      try {
        const texto = await ctx.api.getRaw(c.rota);
        ctx.download(c.arquivo, texto);
        toast("ok");
      } catch (e) {
        toast((e as { message?: string }).message ?? "erro");
      }
    };
    card.append(btn);
    grid.append(card);
  }

  // Cards informativos: render nodes e rede de treino.
  const info: [Record<Lang, string>, Record<Lang, string>][] = [
    [
      { pt: "Render nodes (Kaggle/Colab/PC)", en: "Render nodes (Kaggle/Colab/PC)" },
      {
        pt: "A ARKHER gera o trabalho; você roda o notebook no seu próprio Kaggle (P100/T4, ~30h de GPU/semana gratuitas) e devolve os artefatos. Nenhum acesso externo ao runtime.",
        en: "ARKHER generates the job; you run the notebook on your own Kaggle (P100/T4, ~30h free GPU/week) and return the artifacts. No external access at runtime.",
      },
    ],
    [
      { pt: "Rede de treino (workers)", en: "Training network (workers)" },
      {
        pt: "Treinamento distribuído opcional: os seus workers geram amostras licenciadas e fine-tunam o modelo ARKHER-1 localmente. Tudo registrado na aba Cérebro.",
        en: "Optional distributed training: your workers generate licensed samples and fine-tune ARKHER-1 locally. Everything is logged in the Cérebro tab.",
      },
    ],
    [
      { pt: "Hugging Face — sync de checkpoints", en: "Hugging Face — checkpoint sync" },
      {
        pt: "Envie os checkpoints treinados para o seu próprio repositório HF privado; o produto só usa os pesos que você treinar.",
        en: "Push trained checkpoints to your own private HF repo; the product only uses weights you train.",
      },
    ],
    [
      { pt: "Sempre ligado — auto-ligar/auto-recuperar", en: "Always-on — auto-start/self-heal" },
      {
        pt: "Alternativa legítima ao religamento manual: systemd com Restart=always (deploy/arkher.service), Docker com healthcheck, e o vigia deploy/arkher-watchdog.sh. O serviço volta sozinho de qualquer queda, na sua própria máquina.",
        en: "Legitimate alternative to manual reboots: systemd with Restart=always (deploy/arkher.service), Docker with healthcheck, and the deploy/arkher-watchdog.sh watchdog. The service recovers on its own, on your own machine.",
      },
    ],
  ];
  for (const [nome, desc] of info) {
    const card = el("div", { class: "tool-card" });
    card.append(el("h3", {}, nome[L]), el("p", {}, desc[L]));
    grid.append(card);
  }

  return root;
}
